/*
 * Federal and state tax math for the teaching tool. Deliberate
 * simplifications, stated in the UI: standard deduction only, wage income
 * only, no credits beyond the state exemption credits, no local taxes. The
 * goal is the *structure* — marginal vs. effective rates, how a paycheck
 * splits, and how pre-tax saving changes the picture — not a filing estimate.
 */
import { annuityFV } from '../../lib/finance'
import {
  BRACKETS,
  FICA,
  STANDARD_DEDUCTION,
  type Bracket,
  type FilingStatus,
} from './data2026'
import { STATE_TAXES } from './stateData2026'

export interface BracketSegment {
  rate: number
  from: number
  to: number
  /** Dollars of THIS taxpayer's taxable income that land in this bracket. */
  amount: number
  /** Tax generated by this bracket. */
  tax: number
  /** True if this is the taxpayer's top (marginal) bracket. */
  isMarginal: boolean
}

export interface IncomeTaxResult {
  taxable: number
  segments: BracketSegment[]
  tax: number
  /** Rate on the NEXT dollar earned. */
  marginalRate: number
  /** tax / taxable (0 when taxable is 0). */
  effectiveRateOnTaxable: number
}

/**
 * Fill any bracket schedule with taxable income — the one mechanism federal
 * and state systems share. Keeps empty brackets too: the visualization shows
 * every container, filled or not, so the full structure stays visible.
 */
export function computeBracketTax(
  taxable: number,
  brackets: Bracket[]
): { segments: BracketSegment[]; tax: number; marginalRate: number } {
  const t = Math.max(0, taxable)
  const segments: BracketSegment[] = []
  let from = 0
  let tax = 0
  let marginalRate = brackets[0]?.rate ?? 0

  for (const b of brackets) {
    const amount = Math.max(0, Math.min(t, b.upTo) - from)
    const segTax = amount * b.rate
    tax += segTax
    if (amount > 0) marginalRate = b.rate
    segments.push({ rate: b.rate, from, to: b.upTo, amount, tax: segTax, isMarginal: false })
    from = b.upTo
  }
  // Mark the marginal bracket (the last one that received income).
  for (let i = segments.length - 1; i >= 0; i--) {
    if (segments[i].amount > 0) {
      segments[i].isMarginal = true
      break
    }
  }

  return { segments, tax, marginalRate }
}

export function computeIncomeTax(taxable: number, status: FilingStatus): IncomeTaxResult {
  const t = Math.max(0, taxable)
  const { segments, tax, marginalRate } = computeBracketTax(t, BRACKETS[status])
  return {
    taxable: t,
    segments,
    tax,
    marginalRate,
    effectiveRateOnTaxable: t > 0 ? tax / t : 0,
  }
}

export interface StateTaxResult {
  code: string
  name: string
  hasTax: boolean
  /** The state's income offset (standard deduction + exemption, where offsets). */
  deduction: number
  taxable: number
  /** Exemption-style credit subtracted from the bracket tax, if any. */
  credit: number
  tax: number
  /** State rate on the NEXT taxable dollar. */
  marginalRate: number
  /** The state's own bracket containers — empty for no-tax states. */
  segments: BracketSegment[]
  note?: string
}

export function computeStateTax(
  gross: number,
  contribution401k: number,
  status: FilingStatus,
  stateCode: string
): StateTaxResult {
  const cfg = STATE_TAXES[stateCode]
  const g = Math.max(0, gross)
  const k = Math.min(Math.max(0, contribution401k), g)
  const base = { code: stateCode, name: cfg.name, note: cfg.note }

  if (!cfg.brackets) {
    return {
      ...base,
      hasTax: false,
      deduction: 0,
      taxable: 0,
      credit: 0,
      tax: 0,
      marginalRate: 0,
      segments: [],
    }
  }

  const deduction = cfg.deduction?.[status] ?? 0
  const taxable = Math.max(0, g - k - deduction)
  const { segments, tax: bracketTax, marginalRate } = computeBracketTax(
    taxable,
    cfg.brackets[status]
  )
  const credit = Math.min(cfg.credit?.[status] ?? 0, bracketTax)
  const tax = bracketTax - credit

  return { ...base, hasTax: true, deduction, taxable, credit, tax, marginalRate, segments }
}

/**
 * The whole year's bill — federal income tax + state income tax + payroll —
 * as a single number. Exported for the rate chart, which sweeps it across
 * incomes; computePaycheck uses it for the all-in marginal rate.
 */
export function totalTaxAt(
  gross: number,
  status: FilingStatus,
  contribution401k: number,
  stateCode: string
): number {
  const g = Math.max(0, gross)
  const k = Math.min(Math.max(0, contribution401k), g)
  const taxable = Math.max(0, g - k - STANDARD_DEDUCTION[status])
  const federal = computeBracketTax(taxable, BRACKETS[status]).tax
  const state = computeStateTax(g, k, status, stateCode).tax
  const socialSecurity = FICA.ssRate * Math.min(g, FICA.ssWageBase)
  const medicare = FICA.medicareRate * g
  const additionalMedicare =
    FICA.additionalMedicareRate * Math.max(0, g - FICA.additionalMedicareThreshold[status])
  return federal + state + socialSecurity + medicare + additionalMedicare
}

export interface PaycheckResult {
  gross: number
  contribution401k: number
  standardDeduction: number
  taxable: number
  federalTax: number
  socialSecurity: number
  medicare: number
  additionalMedicare: number
  takeHomeYear: number
  takeHomeMonth: number
  /** The whole bill in dollars: federal income + state income + payroll. */
  totalTax: number
  /** The effective rate: all taxes as a share of gross. */
  totalTaxRate: number
  /** What the NEXT dollar of wages pays, all taxes in — income tax plus payroll. */
  marginalAllInRate: number
  incomeTax: IncomeTaxResult
  state: StateTaxResult
}

export function computePaycheck(
  gross: number,
  status: FilingStatus,
  contribution401k: number,
  stateCode: string
): PaycheckResult {
  const g = Math.max(0, gross)
  const k = Math.min(Math.max(0, contribution401k), g)

  // 401(k) deferrals reduce income tax but NOT payroll (FICA) tax — FICA is
  // computed on gross wages. Nearly every taxing state follows the federal
  // pre-tax treatment of deferrals (PA is the exception, noted in its data).
  const standardDeduction = STANDARD_DEDUCTION[status]
  const taxable = Math.max(0, g - k - standardDeduction)
  const incomeTax = computeIncomeTax(taxable, status)
  const state = computeStateTax(g, k, status, stateCode)

  const socialSecurity = FICA.ssRate * Math.min(g, FICA.ssWageBase)
  const medicare = FICA.medicareRate * g
  const additionalMedicare =
    FICA.additionalMedicareRate * Math.max(0, g - FICA.additionalMedicareThreshold[status])

  const totalTax = incomeTax.tax + state.tax + socialSecurity + medicare + additionalMedicare
  const takeHomeYear = g - k - totalTax

  // The all-in marginal rate, taken numerically over the next $100 of wages
  // so bracket edges, the SS wage cap, and the Medicare surtax threshold all
  // come out right without special cases.
  const marginalAllInRate = (totalTaxAt(g + 100, status, contribution401k, stateCode) - totalTax) / 100

  return {
    gross: g,
    contribution401k: k,
    standardDeduction,
    taxable,
    federalTax: incomeTax.tax,
    socialSecurity,
    medicare,
    additionalMedicare,
    takeHomeYear,
    takeHomeMonth: takeHomeYear / 12,
    totalTax,
    totalTaxRate: g > 0 ? totalTax / g : 0,
    marginalAllInRate,
    incomeTax,
    state,
  }
}

export interface RothVsTraditionalResult {
  /** After-tax value at retirement, Traditional (taxed on the way out). */
  traditional: number
  /** After-tax value at retirement, Roth (taxed on the way in). */
  roth: number
  /** Pre-tax balance the Traditional account shows before withdrawal tax. */
  traditionalPreTax: number
  /** The equal-sacrifice Roth contribution: C × (1 − tax rate now). */
  rothContribution: number
}

/*
 * Apples-to-apples framing: the saver gives up the same take-home pay either
 * way. $C of pre-tax salary funds either a $C Traditional contribution, or a
 * $C·(1−t_now) Roth contribution (the rest goes to tax today). Then:
 *   Traditional after tax  = FV(C) · (1 − t_retirement)
 *   Roth (never taxed again) = FV(C) · (1 − t_now)
 * so whichever tax rate is LOWER — now vs. in retirement — wins, and equal
 * rates tie exactly. The FV factor is identical and cancels.
 */
export function computeRothVsTraditional(
  annualContribution: number,
  years: number,
  returnPct: number,
  taxNowPct: number,
  taxRetirePct: number
): RothVsTraditionalResult {
  const r = returnPct / 100
  const fvPreTax = annuityFV(annualContribution, r, years)
  const rothContribution = annualContribution * (1 - taxNowPct / 100)
  return {
    traditionalPreTax: fvPreTax,
    traditional: fvPreTax * (1 - taxRetirePct / 100),
    roth: annuityFV(rothContribution, r, years),
    rothContribution,
  }
}
